name: Quality Assurance

on:
  pull_request:
    branches:
      - "1.x"
      - "2.x"

jobs:
  qa:
    name: QA
    uses: QuingKhaos/khaosci/.github/workflows/qa.yml@2d2ad15a401bf43d8f458d18f1f9f810ba9209dd
